# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tweeter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'AFNetworking'
    pod 'BDBOAuth1Manager'

  # Pods for Tweeter

  target 'TweeterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TweeterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
